### PR TITLE
Renamed packages to meteor-gazelle:module instead of meteor-gazelle-m…

### PR DESCRIPTION
**Pull request by borghunter-wcd**
As mentioned in #121, packages can keep the "meteor-gazelle:module" naming scheme, but folders cannot.

### CODE REVIEW

**Comment by ghost** [comment]
@borghunter-wcd This looks good to me. Does it resolve issue #129? If not please include that fix into this PR.

**Comment by borghunter-wcd** [comment]
@ajax-wcd yeah, i can take care of that later. I'll have to play with it a bit, not sure if `api.addFiles` uses the package name or the folder name.

**Comment by borghunter-wcd** [comment]
Seems to use the folder name, so #130 fixes the bug.

**Comment by thomwiggers** [comment]
lgtm :+1:

**Comment by thomwiggers** [comment]
oops that was the wrong button.

**Pull request merged**
