### PR TITLE
Add header dropdown menus

### PR DESCRIPTION
**Pull request by sneakysneakysneaky**
Adds dropdown menus to the header per @chriscubellis's mockups.

The styles are complete, but the actual links & routes are hard-coded & completely made up. They should obviously be made configurable.

### CODE REVIEW

**Comment by ghost** [comment]
@sneakysneakysneaky All the JS looks good to me. 

I would like to see the menu moved into its own namespace or placed under Gazelle.menu with a functions to manage the menu items. This is so other packages could add their own menu items. For example rather than us defining the music torrents menu item, the music torrent package would register the menu item itself.

**Comment by sneakysneakysneaky** [comment]
@ajax-wcd I will start working on the updates to the menu that we discussed last week. In the meantime, this PR can probably be merged unless there is more stylesheet feedback. The stylesheets probably won't change.

**Comment by sneakysneakysneaky** [comment]
Rebased. Will let this PR simmer for a day or so, then merge. I've been working on some stuff for menus, & I would like this in master before i submit that feature.

**Comment by karlbright** [comment]
You should definitely put screenshots/gifs with your PRs. Good practice. Keen to see some of the theme stuff and not sure where to find mockups?

**Comment by sneakysneakysneaky** [comment]
By your command.

snapshot19

**Pull request merged**
