### PR TITLE
Add code standard documentation

### PR DESCRIPTION
**Pull request by sneakysneakysneaky**
Add code standard documentation. Copy content from old wiki page.

### CODE REVIEW

**Comment by salas-wcd** [comment]
Shall i add a part about atom, eslinter or nuclide (facebook ide based on atom).

**Comment by sneakysneakysneaky** [comment]
@salas-wcd, go for it.

Edit: Maybe not eslinter. Vanilla eslint should do fine. Lets not overcomplicate.

**Comment by ghost** [comment]
@salas-wcd Will you be adding those sections or should this be merged as it stands?

**Comment by salas-wcd** [comment]
I will add this today. If not merge and i will do extra pr.

**Comment by salas-wcd** [comment]
Go merge this, I will do another PR for atom.

**Pull request merged**
