### PR TITLE
Add support for optional testing pre-push hook

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
@ajax-wcd Waiting on your go ahead for this

**Comment by sneakysneakysneaky** [comment]
Can install_git_hooks.sh be chmod'ed to +x?

**Comment by ghost** [comment]
@guitarman0831 if all comments are resolved, including sneakysneaky's then merge.

**Comment by ghost** [comment]
Thanks @sneakysneakysneaky, resolved.

**Pull request merged**
