### PR TITLE
WIP: Add basic announcement model

### PR DESCRIPTION
**Pull request by jimrollenhagen**
This does a few things:
- Update meteor packages
- Adds jagi:astronomy and jagi:astronomy-behaviors-timestamps
- Adds a basic model for announcements
- Set eslint max line length to error, not warn, and ignore URLs

### CODE REVIEW

**Comment by salas-wcd** [comment]
Shall we support desktop notifications? What is the priority of such a thing.

**Comment by ghost** [comment]
@salas-wcd Low priority.

**Comment by ghost** [comment]
@jimrollenhagen Is this ready for merge?

**Comment by ghost** [comment]
Closing this PR as it falls under #183

**Pull request closed without merging**
