### PR TITLE
[WIP] General Glossary

### PR DESCRIPTION
**Pull request by TheDevKing**
A continuation of the work by @Malvar relating to issue #164.

I think most of the "difficult" terms are now defined in a sufficiently ambiguous way so as to be generally applicable.

Obviously this still needs more work

### CODE REVIEW

**Comment by jimrollenhagen** [comment]
I know you didn't start it... but why are we putting html in markdown files?

**Comment by salas-wcd** [comment]
I guess it is for table based alignement. Github flovored md support this. Well,  maybe it isn't worth the unreadability. But the rich diff is nice with this.

**Comment by TheDevKing** [comment]
I have no attachment to html over markdown. I just continued the work in the style it was originally written in.

The main difference, as far as I can see, with using html over markdown for this is a reduction in the vertical whitespace between the term and the definition.

**Comment by ghost** [comment]
@TheDevKing How's this coming along?

**Comment by ghost** [comment]
Can the syntax be changed to be more reader friendly with markdown rather than html?

Other that it looks good to me but it's definitely an on going work. Feel free to merge.

**Comment by TheDevKing** [comment]
@guitarman0831 I haven't had a chance to make any more progress on this

@ajax-wcd I just did a quick regex replace to change it to markdown, though it would probably benefit from a styling overhaul

**Comment by ghost** [comment]
@TheDevKing Looks good with the MD. I'm going to merge this.

**Pull request merged**
