### PR TITLE
rename from gazelle-PKG to meteor-gazelle:PKG

### PR DESCRIPTION
**Pull request by ahaym**
As the header says. I decided to go with meteor-gazelle:PACKAGE as opposed to meteor-gazelle-PACKAGE as the former is clearer on the package's role as a subset of meteor-gazelle, rather than a standalone package.

Summary:
- Changed the folder names from gazelle-PACKAGE to meteor-gazelle:package.
- Changed the corresponding names in .meteor/packages and .meteor/versions as well.

### CODE REVIEW

**Comment by ghost** [comment]
@ahaym Looks good. Be sure to close issue #102

**Comment by ahaym** [comment]
@ajax-wcd Am I able to close the issue without write permission or issue ownership? I don't see the close button on the issue page.

**Comment by ghost** [comment]
@ahaym I'm sorry, didn't realize the lack of permissions. The issue will be closed now that you've referenced it after I merge this pull request. Thanks!

**Comment by thomwiggers** [comment]
Um, won't this break the repository for anyone using Windows? afaik, `:` isn't a valid file name character on Windows.

**Comment by ghost** [comment]
@thomwiggers Wow good point. Didn't even occur to me. We may need to change the folder names to meteor-gazelle-something in that case. I'd say if we're using dashes in the folder names than use a dash in the package name as well to avoid confusion.

Sorry for jumping the gun on this one and merging it.

**Comment by borghunter-wcd** [comment]
I learnt this the hard way on another project, but regardless:

The folder names DON'T matter, it just uses the names put in package.js config. The folder could be named "blahblah" and the `name` parameter in the package.js could be "meteor-gazelle:module". So you'd have the best of all world, ":" delimited package names, and folders that don't break windows.

Also, naming the package folder "meteor-gazelle-module" every time just seems incredibly redundant.

**Comment by rhomes-wcd** [comment]
@borghunter-wcd We have swapped it already to follow the '-' delimiter from #124. We could go the ':' route with parameterized package files if we want to flip flop again, however I dont see how "meteor-gazelle-module" vs "meteor-gazelle:module" reduces redundancy.

**Comment by borghunter-wcd** [comment]
@rhomes-wcd oh, i wasn't suggesting that at all for file names, just perhaps the "core" package folders could go without "meteor-gazelle" entirely, and just be named "module", rather than "meteor-gazelle(-|:)module"
But whatever, it's not important, since, like I said, the folder names don't change anything and can be changed in the future if it becomes an actual issue.

However, the module names in "package.js" should be standardized asap and remain unchanged. Using the Meteor ":" notation there is my suggestion.

**Pull request merged**
